import type { Content } from 'pdfmake/interfaces';

// !Complete function with all params: currentPage, pageCount and pageSize
// export const footerSection = (
//   //? currentPage, pageCount and pageSize are auto generated by PDF make
//   currentPage: number,
//   pageCount: number,
//   pageSize: ContextPageSize,
// ): Content => ({
//   text: `page ${currentPage} of ${pageCount} - Page info: height: ${pageSize.height} - width: ${pageSize.width} - orientation: ${pageSize.orientation}`,
//   alignment: 'center',
//   margin: [0, 20, 50, 0],
//   fontSize: 10,
//   bold: true,
// });

export const footerSection = (
  //? currentPage, pageCount and pageSize are auto generated by PDF make
  currentPage: number,
  pageCount: number,
  //   pageSize: ContextPageSize,
): Content => ({
  text: `page ${currentPage} of ${pageCount}`,
  alignment: 'right',
  margin: [0, 10, 35, 0],
  fontSize: 12,
  bold: true,
});
